services: 
  app1:
    container_name: api01
    build: ./hello-world-api
    ports:
      - "3000:3000"
    environment:
      - MESSAGE= ${MESSAGE1}

    
  app2:
    container_name: api02
    build: ./hello-world-api
    ports:
      - "3001:3000"
    environment:
      - MESSAGE= ${MESSAGE2}
    
  app3:
    container_name: api03
    build: ./hello-world-api
    ports:
      - "3002:3000"
    environment:
      - MESSAGE= ${MESSAGE3}
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    
volumes:
  db_data: 